# Generated by Django 3.2.2 on 2022-10-31 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20221030_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='requette_u',
            name='userrr',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile'),
            preserve_default=False,
        ),
    ]
